# Generated by Django 5.0.1 on 2024-01-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_image_tegs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
    ]
