# Generated by Django 5.0.1 on 2024-01-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_image_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
    ]
